### PR TITLE
Add  "add package feature"

### PR DESCRIPTION
**Pull request by howardhu99**
Instructors can add their desire package to our website by typing packages' names and click the button.
The command will automatically write into the default setup.sh file
Remove setup.sh file from git ignore file because we need to keep it on the server for later use.

The default setup.sh file is given by the Gradescope community (https://github.com/guerzh/r_autograde_gradescope)

### CODE REVIEW

**Comment by tbrown122387** [comment]
Do we need a `setup.sh` to be stored? It’s generated on a case-by-case basis right now https://github.com/tbrown122387/autograder_gen_site/blob/63e7388cbcbaba61fc06b9d2464cca81b92ca0ad/R/gen_setup_script.R#L7

**Comment by howardhu99** [comment]
I don't know should we keep it case by case or not. Since every assignment may need different packages if we store all packages in one setup.sh, it may waste a lot of memory. I would say we can let people only get default setup.sh when they open the website.

**Comment by tbrown122387** [comment]
This doesn't appear to work correctly. It doesn't correctly register the packages. Also, I don't think we should store a "default" setup.sh, because there really isn't one. every class and every assignment could use different packages, and the default-ness is built into `genSetupScript`

test

**Comment by howardhu99** [comment]
Thanks for reviewing my code. I am sorry I have a little bit confused about our project right now. Maybe we can discuss it during office hours. Then we can make more progress. Thanks!

**Comment by tbrown122387** [comment]
@Haohao99 my pleasure, sure see you in office hours

**Pull request closed without merging**
